[package]
name = "rusty_thing"
version = "0.1.0"
authors = ["Sebastian Green-Husted <ricecake@tfm.nu>"]

[dependencies.dns]
dns = "*"
[dependencies.websocket]
websocket = "*"
[dependencies.hlua]
git = "https://github.com/indefini/hlua.git"
hlua = "*"
[dependencies.ozone]
ozone = "*"
